<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PocketMoney.Application.Contract/PocketMoney.Application.Contract.csproj" />
    <ProjectReference Include="../PocketMoney.Application.Model/PocketMoney.Application.Model.csproj" />
    <ProjectReference Include="../../Domain/PocketMoney.Domain/PocketMoney.Domain.csproj" />
    <ProjectReference Include="../../Infrastructure/PocketMoney.Persistence/PocketMoney.Persistence.csproj" />
    <ProjectReference Include="../../Cross Layer/PocketMoney.Global/PocketMoney.Global.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
</Project>
