// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PocketMoney.Persistence.Data;

#nullable disable

namespace PocketMoney.Persistence.Migrations
{
    [DbContext(typeof(PocketMoneyDbContext))]
    partial class PocketMoneyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PocketMoney.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_id");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text")
                        .HasColumnName("details_json");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_audit_logs_household_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("account_id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_id");

                    b.Property<string>("CurrencyKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency_key");

                    b.Property<decimal>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(19, 3)
                        .HasColumnType("numeric(19,3)")
                        .HasDefaultValue(0.000m)
                        .HasColumnName("current_balance");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_hash");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uuid")
                        .HasColumnName("security_stamp");

                    b.Property<byte>("UnsuccessfulLoginAttempts")
                        .HasColumnType("smallint")
                        .HasColumnName("unsuccessful_login_attempts");

                    b.HasKey("Id")
                        .HasName("pk_children");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_children_account_id");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_children_creator_id");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_children_household_id");

                    b.ToTable("children", (string)null);
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCurrencyKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("default_currency_key");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_households");

                    b.ToTable("households", (string)null);
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.HouseholdInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("InvitedByParentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invited_by_parent_id");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invited_email");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_accepted");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_household_invitations");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_household_invitations_household_id");

                    b.HasIndex("InvitedByParentId")
                        .HasDatabaseName("ix_household_invitations_invited_by_parent_id");

                    b.ToTable("household_invitations", (string)null);
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.IpBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BanCount")
                        .HasColumnType("integer")
                        .HasColumnName("ban_count");

                    b.Property<DateTimeOffset>("BannedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_until");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ip_bans");

                    b.HasIndex("IpAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_ip_bans_ip_address");

                    b.ToTable("ip_bans", (string)null);
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HttpRequestInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("http_request_info");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean")
                        .HasColumnName("is_successful");

                    b.HasKey("Id")
                        .HasName("pk_login_attempts");

                    b.HasIndex("IpAddress", "IsSuccessful", "CreatedAt")
                        .HasDatabaseName("ix_login_attempts_ip_address_is_successful_created_at");

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.Parent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("ParentPinHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parent_pin_hash");

                    b.HasKey("Id")
                        .HasName("pk_parents");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_parents_household_id");

                    b.HasIndex("Id", "HouseholdId")
                        .IsUnique()
                        .HasDatabaseName("ix_parents_id_household_id");

                    b.ToTable("parents", (string)null);
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(13, 3)
                        .HasColumnType("numeric(13,3)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_id");

                    b.Property<string>("CurrencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency_key");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid")
                        .HasColumnName("household_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reason");

                    b.Property<decimal>("RemainingAfter")
                        .HasPrecision(19, 3)
                        .HasColumnType("numeric(19,3)")
                        .HasColumnName("remaining_after");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CreatorId")
                        .HasDatabaseName("ix_transactions_creator_id");

                    b.HasIndex("HouseholdId")
                        .HasDatabaseName("ix_transactions_household_id");

                    b.HasIndex("ChildId", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_transactions_child_id_created_at_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.Child", b =>
                {
                    b.HasOne("PocketMoney.Domain.Entities.Parent", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_children_parents_creator_id");

                    b.HasOne("PocketMoney.Domain.Entities.Household", "Household")
                        .WithMany("Children")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_children_households_household_id");

                    b.Navigation("Creator");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.HouseholdInvitation", b =>
                {
                    b.HasOne("PocketMoney.Domain.Entities.Household", "Household")
                        .WithMany("Invitations")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_household_invitations_households_household_id");

                    b.HasOne("PocketMoney.Domain.Entities.Parent", "InvitedByParent")
                        .WithMany()
                        .HasForeignKey("InvitedByParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_household_invitations_parents_invited_by_parent_id");

                    b.Navigation("Household");

                    b.Navigation("InvitedByParent");
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.Parent", b =>
                {
                    b.HasOne("PocketMoney.Domain.Entities.Household", "Household")
                        .WithMany("Parents")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parents_households_household_id");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("PocketMoney.Domain.Entities.Child", "Child")
                        .WithMany("Transactions")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_children_child_id");

                    b.HasOne("PocketMoney.Domain.Entities.Parent", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_parents_creator_id");

                    b.HasOne("PocketMoney.Domain.Entities.Household", "Household")
                        .WithMany("Transactions")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_households_household_id");

                    b.Navigation("Child");

                    b.Navigation("Creator");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.Child", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PocketMoney.Domain.Entities.Household", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Invitations");

                    b.Navigation("Parents");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
